name: Build and Push Go App

on:
  push:
    branches:
      - main
      - develop
      - release/**
      - feature/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
      id: go

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare
      id: prep
      run: |
        BRANCH_NAME_UNDERSCORES=${GITHUB_REF_NAME////} # Replace '/' with ''
        BRANCH_NAME=${BRANCH_NAME_UNDERSCORES,,} # Convert to lowercase
        COMMIT=${GITHUB_SHA::6} # Get the short SHA
        echo "BRANCH_NAME=${BRANCH_NAME}" >> "$GITHUB_ENV"
        echo "COMMIT=${COMMIT}" >> "$GITHUB_ENV"

    - name: Print env vars
      id: print_env
      run: |
        printf 'REGISTRY: %s\n' "$REGISTRY"
        printf 'IMAGE_NAME: %s\n' "$IMAGE_NAME"
        printf 'BRANCH_NAME: %s\n' "$BRANCH_NAME"
        printf 'COMMIT: %s\n' "$COMMIT"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64  # Only build for amd64
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}